/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_EncryptDecrypt_Decrypt */

#ifndef _Included_test_EncryptDecrypt_Decrypt
#define _Included_test_EncryptDecrypt_Decrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_EncryptDecrypt_Decrypt
 * Method:    RSAInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_test_EncryptDecrypt_Decrypt_RSAInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     test_EncryptDecrypt_Decrypt
 * Method:    DecryptData
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_test_EncryptDecrypt_Decrypt_DecryptData
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
