package chat;

import javax.swing.*;
import java.net.*;
import java.io.*;

public class Chater extends JFrame {
    ServerSocket server;
    Socket client;
    Socket connection;
    InputStream is;
    OutputStream os;
    BufferedReader br;
    PrintWriter pw;
    ReceiveThread rt;
    
    /** Creates new form Chating */
    public Chater() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        araMsg = new JTextArea();
        txtMsg = new JTextField();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        txtPortNumber = new JTextField();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jLabel2 = new JLabel();
        txtAddress = new JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        getContentPane().add(araMsg, java.awt.BorderLayout.CENTER);

        txtMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMsgActionPerformed(evt);
            }
        });
        txtMsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMsgKeyTyped(evt);
            }
        });

        getContentPane().add(txtMsg, java.awt.BorderLayout.SOUTH);

        jLabel1.setText("\ud3ec\ud2b8");
        jPanel1.add(jLabel1);

        txtPortNumber.setText("2000");
        jPanel1.add(txtPortNumber);

        jButton1.setText("\uc11c\ubc84\ub418\uae30");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton1);

        jButton2.setText("\ud074\ub77c\uc774\uc5b8\ud2b8\ub418\uae30");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton2);

        jLabel2.setText("\uc8fc\uc18c");
        jPanel1.add(jLabel2);

        txtAddress.setText("localhost");
        jPanel1.add(txtAddress);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }

    private void txtMsgActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your handling code here:
        if (connection == null& client == null)
            return;

        araMsg.append(txtMsg.getText() + "\n");
        
        pw.println(txtMsg.getText());
        pw.flush();
        txtMsg.setText("");
        
    }

    private void txtMsgKeyTyped(java.awt.event.KeyEvent evt) {
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your handling code here:
        try {
            client = new Socket("localhost", 2000);
            is = client.getInputStream();
            os = client.getOutputStream();
        } catch (IOException ioe) {
        }
        br = new BufferedReader(new InputStreamReader(is));
        pw = new PrintWriter(new OutputStreamWriter(os));
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        araMsg.append("������ �����\n");
        rt = new ReceiveThread(this);
        rt.start();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your handling code here:
        try {
            server = new ServerSocket(2000);
            connection = server.accept();
            is = connection.getInputStream();
            os = connection.getOutputStream();
        } catch (IOException ioe) {
        }
        br = new BufferedReader(new InputStreamReader(is));
        pw = new PrintWriter(new OutputStreamWriter(os));
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        araMsg.append("Ŭ���̾�Ʈ�� �����\n");
        rt = new ReceiveThread(this);
        rt.start();
        
    }
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);        

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Chater chater = new Chater();
        chater.show();
        //chater.setSize(500, 500);
    }        

    
    // Variables declaration - do not modify
    JTextArea araMsg;
    private JButton jButton1;
    private JButton jButton2;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JPanel jPanel1;
    private JTextField txtAddress;
    private JTextField txtMsg;
    private JTextField txtPortNumber;
    // End of variables declaration
    
}

class ReceiveThread extends Thread {
    Chater parent;
    
    public ReceiveThread(Chater chater)
    {
        parent = chater;
    }
    public void run()
    {
        while (true)
        {
            try {
                parent.araMsg.append(parent.br.readLine() + "\n");
            } catch (IOException ioe) {
            }
        }
    }
}