/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Encrypt */

#ifndef _Included_Encrypt
#define _Included_Encrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Encrypt
 * Method:    RSAInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Encrypt_RSAInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Encrypt
 * Method:    EncryptData
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_Encrypt_EncryptData
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
