/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITest
 * Method:    ToDouble
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_JNITest_ToDouble
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNITest
 * Method:    Concat
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNITest_Concat
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
